development:
  user: fedoraAdmin
  password: fedoraAdmin
  timeout: 120
  url: http://127.0.0.1:8983/fedora
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  timeout: 120
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/fedora-test" %>
production:
  user: fedoraAdmin
  password: changeme
  timeout: 120
  url: http://iaminproduction.edu
  timeout: 120
cucumber:
  <<: *TEST
