defaults: &defaults
  stage_root: /tmp/pulstore-staging
  fits_download: https://fits.googlecode.com/files/fits-0.6.2.zip
  fits_dir: fits
  voyager_datasource: http://diglib.princeton.edu/tools/v2m/
  pulfa_datasource: http://findingaids.princeton.edu/collections/
  noid_template: .zdeeek # .reeddeeddk <- Sufia
  minter_statefile: noid-minter-state #will be in app root
  id_namespace: puls
  lae_recap_code: rcpxr
  lae_rights_boilerplate: "This digital reproduction is intended to support research, teaching, and private study. Users are responsible for determining any copyright questions."


development:
  <<: *defaults
  noid_template: d.zdeeek

test:
  <<: *defaults
  noid_template: t.zdeeek

production:
  <<: *defaults
  noid_template: .zdeeek
