uva-only:
  - uva-only
archivist:
  - archivist1@example.com
donor:
  - donor1@example.com
researcher:
  - researcher1@example.com
patron:
  - patron1@example.com
admin_policy_object_editor:
  - archivist1@example.com
all_project_discover:
  - joetest@university.edu
lae_project_discover:
  - joetest@university.edu
all_project_readers:
  - joetest@university.edu
all_project_writers:
  - joetest@university.edu
lae_project_readers:
  - joetest@university.edu
lae_project_writers:
  - joetest@university.edu
