development:
  archivist:
    - archivist1@example.com
  all_project_discover:
    - joetest@university.edu
  lae_project_discover:
    - joetest@university.edu
  all_project_readers:
    - joetest@university.edu
  all_project_writers:
    - joetest@university.edu
  lae_project_readers:
    - joetest@university.edu
  lae_project_writers:
    - joetest@university.edu

test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com
  all_project_discover:
    - joetest@university.edu
  lae_project_discover:
    - joetest@university.edu
  all_project_readers:
    - joetest@university.edu
  all_project_writers:
    - joetest@university.edu
  lae_project_readers:
    - joetest@university.edu
  lae_project_writers:
    - joetest@university.edu
